version: "3"
 
services:
  jaeger:
    image: "jaegertracing/all-in-one:1.52"
    ports:
      - "16686:16686"
    expose:
      - 4317
      - 4318
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./.aws:/root/.aws/
    ports:
      - 4317:4317 # OTLP gRPC receiver
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
    depends_on:
      - jaeger
  # Flask アプリケーション
  flask-app:
    build:
      context: ./flask
    ports:
      - "3000:3000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector
  # AWS X-Ray Daemon
  xray-daemon:
    image: public.ecr.aws/xray/aws-xray-daemon:latest
    ports:
      - "2000:2000/udp"
      - "2000:2000/tcp"
    environment:
      - LOG_LEVEL=info
      - AWS_REGION=us-east-1
      - LOCAL_MODE=true